# Basic site settings
title: "Sebastian's Portfolio"
description: "Software Engineer | Full-Stack Developer | Creative Technologist"
theme: jekyll-theme-minimal
baseurl: "" # Keep empty unless your site is in a subdirectory
url: "https://github.com/Sebas-D-Dev"

# Author details
author:
  name: "Sebastian"
  email: "sebas.t.nait@gmail.com"
  github: "https://github.com/Sebas-D-Dev"
  linkedin: "https://www.linkedin.com/in/YOUR_LINKEDIN_PROFILE"

# Navigation links
navbar-links:
  Home: "/"
  Projects: "/projects"
  About: "/about"
  Contact: "/contact"

# Plugins (optional, for extended functionality)
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Social media & contact
social:
  github: "https://github.com/YOUR_GITHUB_USERNAME"
  linkedin: "https://www.linkedin.com/in/sebastian-torres-cs"
  email: "sebas.t.nait@gmail.com"

# Enable GitHub Pages features
markdown: kramdown
highlighter: rouge

# Additional settings
show_downloads: true # Display repo download links
